name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv
      - name: Run a single command in the devenv shell
        run: devenv shell treefmt --ci
      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test
      # - name: Run a multi-line command in the devenv shell
      #   shell: devenv shell -- bash -e {0}
      #   run: |
      #     hello
      #     say-bye
