version: "3"
tasks:
  ansible:requirements-setup:
    dir: ./ansible/
    cmds:
      - ansible-galaxy install -r ./requirements.yaml
  vagrant:down:
    aliases:
      - down
    cmds:
      - vagrant destroy -f {{.CLI_ARGS}}
  vagrant:up:
    # TODO: this breaks my SSH connection when machines are being created the first time (host1 -(x)> host2 -> vagrant)
    deps:
      - ansible:requirements-setup
    cmds:
      - vagrant up {{.CLI_ARGS}}
  kubeconfig:cp:
    vars:
      SERVER_CMD: "vagrant ssh server-0 -- "
      SERVER:
        sh: echo "https://$({{.SERVER_CMD}} hostname -i):6443"
      KUBE_DIR:
        sh: dirname $KUBECONFIG
    dir: "{{.KUBE_DIR}}"
    cmds:
      - >-
        {{.SERVER_CMD}} sudo cat /etc/rancher/k3s/k3s.yaml
        | yq '.clusters[0].cluster.server = "{{.SERVER}}"'
        > $KUBECONFIG
  age-key:gen:
    cmds:
      - age-keygen -o $SOPS_AGE_KEY_FILE
  jwk:setup:
    dir: ./fake-vault/jwt/
    cmds:
      - |
        step crypto jwk create \
        ./public.jwk \
        ./private.dec.jwk \
        --kty EC \
        --crv P-256 \
        --alg ES256 \
        --use sig \
        --kid desafio-devops-es256-1 \
        --no-password \
        --insecure
      - cmd: sops encrypt --filename-override ./private.enc.jwk --output ./private.enc.jwk ./private.dec.jwk
        ignore_error: true
      - yq -o=json -n '.keys = [load("./public.jwk")]' > ./jwks.json
      - yq -P ./jwks.json
  private.dec.jwk:
    dir: ./fake-vault/jwt/
    sources:
      - ./private.enc.jwk
    generates:
      - ./private.dec.jwk
    cmds:
      - sops --decrypt --output ./private.dec.jwk ./private.enc.jwk
  jwt:gen:
    dir: ./fake-vault/jwt/
    deps:
      - task: private.dec.jwk
    vars:
      ISS: >-
        {{.ISS | default "https://desafio-devops.local"}}
      AUDS: >-
        {{.AUDS | default "service-1,service-2,service-3"}}
      AUDS_FLAGS: >-
        {{range $index, $aud := splitList "," .AUDS}}--aud {{$aud}} {{end}}
      JWT_PAYLOAD: >-
        {{.JWT_PAYLOAD | default "echo {}"}}
    cmds:
      - |
        {{.JWT_PAYLOAD}} \
        | step crypto jwt sign \
        --key ./private.dec.jwk \
        --alg ES256 \
        --kid desafio-devops-es256-1 \
        --iss {{.ISS}} \
        --sub demo-user \
        {{.AUDS_FLAGS}} \
        --exp "$(date -u -d '+1 days' +%s)" \
        | tee ./token.dec.jwt
      - cmd: |
          cat ./token.dec.jwt | step crypto jwt verify \
          --jwks ./jwks.json \
          --iss {{.ISS}} \
          {{.AUDS_FLAGS}} > /dev/null
  tls-certs:cp:
    dir: ./fake-vault/tls/
    cmds:
      - >-
        find $DEVENV_STATE/mkcert -type f -iregex '.*\.pem$' ! -iregex '.*-key\.pem$' -print0
        | xargs -0 -I {} bash -c 'cp "{}" ./$(basename "{}").crt'
      - >-
        find $DEVENV_STATE/mkcert -type f -iregex '.*-key\.pem$' -print0
        | xargs -0 -I {} bash -c 'sops -e --filename-override .enc --output ./$(basename "{}").enc.key "{}"'
  helmfile:sync:
    dir: ./k8s/
    cmds:
      - helmfile repos
      - helmfile --skip-deps -l crd=true sync
      - helmfile --skip-deps -l crd!=true apply
  cluster:wait_until_ready:
    vars:
      SLEEP: "10"
    cmds:
      - cmd: >-
          while 
          kubectl get nodes -o yaml | yq '.items[] | select(.status.conditions[] | select(.type=="Ready") | .status!="True") | .metadata.name'
          | grep -q .; do echo "⏳ Waiting for nodes to be Ready..."; sleep {{.SLEEP}};
          done
          && echo "✅ All nodes are Ready."
  up:
    cmds:
      - task: vagrant:up
        timeout: 5m
      - task: kubeconfig:cp
      - task: cluster:wait_until_ready
        timeout: 90s
      # - task: jwk:setup
      - task: helmfile:sync
      # - k6
  k6:test:
    dir: ./k6/
    deps:
      - task: private.dec.jwk
    cmds:
      - k6 run ./test.js -i 1 --summary-mode full --http-debug=full --log-format json --quiet 2> >(yq -P -p json)
  mtls:test:
    dir: ./k8s/
    env:
      INSTALL_MISCELLANEOUS: "true"
    cmds:
      - helmfile -l installed=false apply
