apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  # profile: demo
  # profile: empty
  # profile: minimal
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    # enableAutoMtls: true
    pathNormalization:
      normalizationType: RFC_3986
      mergeSlashes: true
  components:
    base:
      enabled: true
    pilot: # istiod
      enabled: true
      k8s:
        # replicaCount: 1
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          # limits:
          #   cpu: 1000m
          #   memory: 1024Mi
    cni:
      # TODO: enable cni to avoid NET_(ADMIN|RAW) and future ambient mode
      enabled: false
    ztunnel:
      enabled: false
    istiodRemote:
      enabled: false
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        # k8s:
        #   replicaCount: 1
    egressGateways: []
