grafana:
  admin-password: ENC[AES256_GCM,data:fP2haHhxS4H3Uw==,iv:jLfkurcr44x5WFZ8HmYM0y5q3LP6bM1Fy8fuj/bJ+O0=,tag:0Jv+vp+xO0dsPgGLgtwKag==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWXVyVy9jZVQzODA5UGdw
        TjZtT0wxQk1Ha0Rla0RXeVNsWTI0V21EOXlBCkIwS3hDSGdJU2laemszY1k1WlFF
        OVlEcjJvaFlId0JNazF1Tm5hVG5JSzgKLS0tIG5yU0FxZmkrZ3UyTnh6MEdtdm9p
        YzZKNUs1bGxRc290VUluWUFMSm00ZGMKY3CJuxq4VpN4YCSKAd5I4XVQNiylos7w
        v3ePO3zt4wc8n8/uDk0t8SREM1qIkZGD7mjMNsqcwFtIjYDctL4rEg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1449c5yz86myssegmxpdusyfhdxp9q8nxnd8dqgvg2ca87nq4r4tqsaxgyu
  lastmodified: "2026-09-21T16:47:34Z"
  mac: ENC[AES256_GCM,data:WdfG6eWY+oLNTzC5lx503lsdOhsALp2pzKLIzRYAzOVMNYf/GOZQX068cILtHIoGeBYihnkqpfhPijP+8te6qDQ6J4ACTf74T4mPBL1ZoQNrOfcvrRu4/ke/5Fi10YbdMOJQgjJNHYSl/U3i+pc9QvHdDTV92jIsksnr0CpOMA4=,iv:44tgozwp+zAdyy/uUrArAD4MLF6AAGOoX3Oz4ozD1J0=,tag:UTwHgbdvl0jWNlcokvBdQw==,type:str]
  pgp:
    - created_at: "2026-09-21T16:47:33Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA+M+Lk6UIEdnARAAlymmR+bVemd6CD4jZrgcL+qNgGbQaaekOWaR76RnW+lz
        shCXwD0R+z/g2i6jowPrsHsGo9Zb5G587nLRqfzW/ulAr2r4oQD0imyvoFGT8J6I
        KA+PEzDLNxvyR7zjORZOeh5UNxqexziwtRj2bKptVitpEL/xxLOkUpr61iGCVS3i
        FSUxkfNwk166cXKthWSBaIvHcxT0UCK/qXVQrjALOOes8kDu5ROmj3pS/ETjlQvm
        8tWSOu5Tv6B8Ecf2OVty/3a0FWjQwuh8NpNeDOWXnGtmlixVsoOYmAiff4Fj/63w
        /ivloLO81aOFUl5Haeq6/jlSmfSJGUVGpwj01wSWor1GKaGgNEpAKEdeW6vPDViR
        CEyqe8hMLcdyFOHEK2NvOCXsZU0V7wOyGmN4saj2LvA+ro2M8JTbgaH0vw1eSCHR
        knqg1Hg2ZJpveZnCmygi/ZcN/JAsbAfnaQyZvIPdEBW6ykjf6rf2YFobeqHyKA8i
        F4tIM0/Magn6+r/DGp3qvdgfhU6zaiw1Kmczii/syoAy6pME2ULO2BGyZMjKhOor
        3zG/PYiYEBFQDipASR4To6nfibG4xEdweEbQDO6qvrVzWlIXxcoNhmTGwtgSApoV
        F8uW8JjseQl1WjHJ977mM9WHvd5uv2rlM29orEZ9rydU1lIqFcMSzjMIPshVxjfS
        XgHNfAYxyhYJ9j5SNL+nWKsq4G+z8yEE0M+sC/KDjIjypfwSuJKhWoH8uoWufaUq
        87YOPF4An61M691RrHj7EKpTE4ZakXKPLQYOYVf6z4AcPaIQzUkuiHHQLfopDgY=
        =xfoC
        -----END PGP MESSAGE-----
      fp: 51bbb719db9a3f8a928a4d5c9d76b9d8e1e20e99
  unencrypted_suffix: _unencrypted
  version: 3.13.3
