# https://github.com/k3s-io/k3s-ansible/blob/a3bf02f069ad252728fcd588dc879adbc1e7e7f5/playbooks/site.yml
---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: airgap
    - role: raspberrypi

- name: Setup K3S server
  hosts: server
  gather_facts: false
  become: true
  roles:
    - role: k3s_server

- name: Setup K3S agent
  hosts: agent
  gather_facts: false
  become: true
  roles:
    - role: k3s_agent
